### ISSUE TITLE
Feature request: Grid/Ticks/Axis in front of data

### ISSUE THREAD

**Issue by rjdverbeek-tud** [sciapp/gr#103]
Feature request: user option to allow grid/ticks/axis be plotted in front of the data.

A filled polygon will always plot in front of the grid/ticks/axis. Due to this the grid/ticks/axis will disappear. Even if you don't want that. I can't find any options to indicate that the grid/ticks/axis must be plotted in front of the data.

In the following plot the plotted data (filled areas) is currently in front of the grid, ticks, and axis border.
![74274895-280ed700-4d13-11ea-81e4-2e73957ea024](https://user-images.githubusercontent.com/54448042/74413601-05c6a780-4e40-11ea-89db-2ab484ea9975.png)

**Comment by jheinen** [comment]
How did you create the graph? Did you use a convenience function or several low-level GR commands? In the latter case, you could simply change the drawing order ...

**Comment by rjdverbeek-tud** [comment]
I used PLOTS.JL with GR as backend. Within PLOTS i plotted the map by loading a shp file, and converting it to two vectors (lat/lon). This I used for plotting the map. Furthermore, I used PLOTS to specify the grid, and axis.

I will have a look if it makes a difference for PLOTS to plot it in a different order.

**Comment by rjdverbeek-tud** [comment]
It looks like PLOTS.jl will plot the grid and ticks first and then the data. I will reopen my feature with them. Wkr. Rene
