### ISSUE TITLE
Considering Blend2d for rendering

### ISSUE THREAD

**Issue by mantielero** [sciapp/gr#109]
It looks like [Blend2d](https://blend2d.com/) has very [good performance](https://blend2d.com/performance.html). It could be a good fit for GR.

**Comment by FlorianRhiem** [comment]
Hello, thank you for this suggestion!
Looking at the performance comparison to Cairo in particular and some of its features, it could definitely be useful to have a GKS plugin for Blend2D. Though at this time there seems to be a lot of functionality that is [planned but still missing](https://blend2d.com/roadmap.html) from Blend2d, e.g. output to PNGs is marked as pending and font management is marked as in progress, so I think we might need to wait some more and see how the library matures.
