### ISSUE TITLE
Huge installation size of GR on Windows

### ISSUE THREAD

**Issue by jaakkor2** [sciapp/gr#110]
I installed https://github.com/JuliaPlots/Plots.jl that depended on https://github.com/jheinen/GR.jl that installed GR from this repo.

With version of GR.jl 0.48.0, on Windows `.julia\packages\GR` folder size is 301.8 MB.  Biggest contributor seems to be `.julia\packages\GR\yMV3y\deps\gr\bin\libGLESv2d.dll` with size 179.8 MB.

Looking around the net, this file seems to be the debug version of `libGLESv2.dll` sized 3.8 MB that is included as well.

Would it be possible to get rid of the `libGLESv2d.dll`?  Tests on Julia pass without that file.

**Comment by FlorianRhiem** [comment]
Hello, thank you for reporting this!
This library was included as a part of our Qt5 runtime archive, but it seems to have been in there by mistake as we do not use any other debug libraries for Qt5. I have removed the library from that Qt5 runtime archive, so it should not be part of any future GR builds.
