### ISSUE TITLE
Fix for building on FreeBSD

### ISSUE THREAD

**Issue by ko56** [sciapp/gr#125]
All that is needed for the master branch to compile on FreeBSD 12 is this fix in
gr-master/lib/gr3/gr3_internals.h:

#elif defined(__linux__) || defined(__FreeBSD__)
/* OpenGL Extension to the X Window System (GLX) on Linux */
#define GR3_USE_GLX
#include "gr3_glx.h"
#elif defined(_WIN32)

**Comment by FlorianRhiem** [comment]
Hello, thank you for the hint! I've merged it into develop, so it'll be part of the next release. I don't think we have any FreeBSD developers at this time, so if you run into any other issues with GR on FreeBSD, please let us know or open a pull request.

**Comment by ko56** [comment]
Thanks. I will let you know if there are other problems.
