### ISSUE TITLE
Duplicated function declarations in the header files [grm/interaction.h]

### ISSUE THREAD

**Issue by kojix2** [sciapp/gr#130]
Hi GR developers!

In the file below, the function declarations appear to be duplicated.

https://github.com/sciapp/gr/blob/a0ecb281f7eedcbf24cd2ac43a82557ad8817e72/lib/grm/interaction.h#L35-L39

Please close this issue if there are no problems.

Thank you.

**Comment by IngoMeyer441** [comment]
Thanks for your hint! The duplicate entries are removed in commit efb5b116d4adc2c72ce3618e0c2d759b9894a762.
