### ISSUE TITLE
Fix for FreeBSD

### ISSUE THREAD

**Issue by ko56** [sciapp/gr#131]
In lib/gr3/gr3_internals.h, the previous fix for FreeBSD was incorrectly applied:

 #elif defined(__linux__) || defined(__FreeBSD__)
/* OpenGL Extension to the X Window System (GLX) on Linux or FreeBSD */
#define GR3_USE_GLX
#include "gr3_glx.h"
#elif defined(_WIN32)

The __ around FreeBSD are currently missing.

**Comment by FlorianRhiem** [comment]
Thanks! This has been fixed in cb427c391c525573972817822d02710fb8b2f2a8.
