### ISSUE TITLE
Is it possible to use GR in imgui/CImGui?

### ISSUE THREAD

**Issue by yadmtr** [sciapp/gr#133]
Is there a way to use the GR [or [GR.jl](https://github.com/jheinen/GR.jl) (or [GRUtils](https://github.com/heliosdrm/GRUtils.jl))] with 
[imgui](https://github.com/ocornut/imgui) [[CImGui.jl](https://github.com/Gnimuc/CImGui.jl)] ?

How can I let GR do the off-screen rendering?, then I can re-render the output of framebuffer as an CImGui.Image object.

My goal is to render into a CImGui.jl widget using GR.

**Comment by yadmtr** [comment]
I found [solution](https://github.com/Gnimuc/CImGui.jl/issues/37#issuecomment-766331936).

**Comment by jheinen** [comment]
I added an example how to use ImGui with low level GR functions ([link](https://github.com/jheinen/GR.jl/blob/master/examples/imgui_ex.jl)).
