### ISSUE TITLE
dependence of gksqt on libqt4 under Ubuntu

### ISSUE THREAD

**Issue by paciorek** [sciapp/gr#136]
We're trying to install the Julia GR package under Ubuntu 20.04 and Julia 1.3.1. The [GR docs](https://gr-framework.org/julia.html) indicate that one needs libqt5 and not libqt4 for most Linux distributions (including Ubuntu), but this is what we see after we install it (installing seems to pull in GR version 0.52), indicating a hard-coded dependency on libqt4. 

```
$ objdump -p /system/linux/julia-1.3.1/share/julia/packages/GR/BwGt2/deps/gr/bin/gksqt | grep NEEDED
  NEEDED               libQtGui.so.4
  NEEDED               libQtNetwork.so.4
  NEEDED               libQtCore.so.4
  NEEDED               libpthread.so.0
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.6

$ ldd /system/linux/julia-1.3.1/share/julia/packages/GR/BwGt2/deps/gr/bin/gksqt 
	linux-gate.so.1 (0xf7f1c000)
	libQtGui.so.4 => not found
	libQtNetwork.so.4 => not found
	libQtCore.so.4 => not found
	libpthread.so.0 => /lib32/libpthread.so.0 (0xf7eca000)
```

**Comment by jheinen** [comment]
Why don't you use the latest stable version (v0.55.0)? Did you try to update the `GR.jl` package?

**Comment by paciorek** [comment]
Yeah, Julia 1.3.1 pulls in v0.52.0 for us. I tried to force it to pull in v0.55.0 but got into dependency version conflicts with the Plots package. We're also getting an illegal instruction with GR v0.55.0 on Julia 1.5.3 but that's a distinct issue from this one...
