### ISSUE TITLE
[BUG] "Send: no error" display when reopen a plot.

### ISSUE THREAD

**Issue by hungpham3112** [sciapp/gr#151]
I have an issue in Plot.jl and they said I should report that in here.

https://github.com/JuliaPlots/Plots.jl/issues/4152

**Comment by jheinen** [comment]
We have identified the problem and fixed it in the development branch. A bugfix release will be tagged soon.

**Comment by jheinen** [comment]
The problem is fixed in v0.64.2, which was released today
