### ISSUE TITLE
Remove that camera rotation and tilt are integer degrees

### ISSUE THREAD

**Issue by GijsBellaard** [sciapp/gr#157]
Honestly this is just ridiculous. Could this please be changed to floats? 

I'm talking about `static void setspace(double zmin, double zmax, int rotation, int tilt)` in `lib/gr/gr.c`.

**Comment by jheinen** [comment]
The question is honestly not very nicely worded. Please use `setspace3d`, e.g.
```
setwindow(-1, 1, -1, 1)
setwindow3d(xmin, xmax, ymin, ymax, zmin, zmax)
setspace3d(-rotation, tilt, 30, 0)
```

**Comment by GijsBellaard** [comment]
Thanks that works :)

But still... why is `setspace` in integer degrees?

**Comment by jheinen** [comment]
... due to compatibility issues with old(er) software

**Comment by GijsBellaard** [comment]
right...
