### ISSUE TITLE
Replace gethostbyname with getaddrinfo

### ISSUE THREAD

**Issue by bkmgit** [sciapp/gr#167]
gethostbyname is deprecated and will not work with IPV6 addresses. It is used at:
- https://github.com/sciapp/gr/blob/master/lib/gr/stream.c#L108
- https://github.com/sciapp/gr/blob/master/lib/gks/socket.c#L212
For more information and examples see
- https://www.man7.org/linux/man-pages/man3/getaddrinfo.3.html
- https://blog.dornea.nu/2015/04/30/gethostbyname-vs.-getaddrinfo/

**Comment by jheinen** [comment]
Thanks for the hint. We will fix this in the next release.

**Comment by bkmgit** [comment]
Thanks. https://github.com/sciapp/gr/commit/a31ca6da5ce72fcaea4ed9250e06500dfa054c8b
