### ISSUE TITLE
Plotting multiple lines using C api

### ISSUE THREAD

**Issue by general-rishkin** [sciapp/gr#175]
How to plot 2 or more lines using the C api? I cannot see an example like the Python `oplot` and calling `polyline` twice does not work.

**Comment by danielkaiser** [comment]
Hi @general-rishkin,

calling `gr_polyline` twice is the correct approach when using the C API. Probably the issue of the second line not visible is related to the problems in #176. Just make sure that you specify the correct world coordinate region with `gr_setwindow(xmin, xmax, ymin, ymax);` before drawing the lines and call `gr_updatews();` after drawing all lines.

**Comment by IngoMeyer441** [comment]
An addition to @danielkaiser's message:

The GR Framework is divided into multiple layers. The equivalent to the Python API is the GRM (GR Meta) layer in C which supports the same plot types as the Python GR package. This example plots sin and cos with GRM:

```c
#include <math.h>
#include <stdio.h>
#include <grm.h>

int main(int argc, char **argv) {
  double plots[2][2][1000];
  int n = sizeof(plots[0][0]) / sizeof(plots[0][0][0]);
  const char *labels[] = {"sin", "cos"};
  grm_args_t *args, *series[2];
  int i;

  for (i = 0; i < n; ++i)
    {
      plots[0][0][i] = i * 2 * M_PI / n;
      plots[0][1][i] = sin(i * 2 * M_PI / n);
    }
  for (i = 0; i < n; ++i)
    {
      plots[1][0][i] = i * 2 * M_PI / n;
      plots[1][1][i] = cos(i * 2 * M_PI / n);
    }

  for (i = 0; i < 2; ++i)
    {
      series[i] = grm_args_new();
      grm_args_push(series[i], "x", "nD", n, plots[i][0]);
      grm_args_push(series[i], "y", "nD", n, plots[i][1]);
    }

  args = grm_args_new();
  grm_args_push(args, "series", "nA", 2, series);
  grm_args_push(args, "labels", "nS", 2, labels);
  grm_args_push(args, "kind", "s", "line");

  grm_plot(args);

  printf("Press any key to continue...\n");
  getchar();

  grm_args_delete(args);

  grm_finalize();
} 
```
Don't forget to link against GRM with `-lGRM`.

**Comment by general-rishkin** [comment]
@danielkaiser : You are correct. This was indeed linked to the issue in [https://github.com/sciapp/gr/issues/176](https://github.com/sciapp/gr/issues/176).

@IngoMeyer441 : Thank you for the example. It is very useful.

**Comment by IngoMeyer441** [comment]
GRM is still work in progress and not documented very well yet. But there are many examples how to use it:

- GRM test / example directory: <https://github.com/sciapp/gr/tree/develop/lib/grm/test/public_api/grm>
- Snoop example which contains all plot types in a row: <https://github.com/sciapp/gr/blob/develop/lib/grm/test/public_api/grm/snoop/snoop.c>
