### ISSUE TITLE
gr 1.3.0 windows  binary missing QT5 

### ISSUE THREAD

**Issue by thomueller** [sciapp/gr#59]
I have installed gr 1.3.0  over pip on Windows x64, but if I try to use it I get the following error message:
**GKS: Qt5 support not compiled in**
The QT5 support seems to be there up to gr 1.1.0, but Nicos needs 1.3.0.

**Comment by FlorianRhiem** [comment]
Hello thomueller,

the gr Python package 1.1.0 requires the GR runtime version 0.28.1, which we did not build with Qt support for 64 bit Windows. Were you perhaps using an existing GR runtime installation?

What we do support on 64 bit Windows is the gksqt Application, which is a 32 bit binary copied from the 32 bit Windows build. As we deploy the required Qt libraries along with gksqt, it might look as if Qt support was provided, but these are all 32 bit binaries.

If you require the Qt plugin on Windows, I recommend that you build the GR runtime on/for your system. You can then use the GRDIR environment variable to let the Python package know where it can find your runtime installation.
