### ISSUE TITLE
feature request: staircase

### ISSUE THREAD

**Issue by nilsbecker** [sciapp/gr#65]
`gr.polyline` draws a linear interpolation from point to point; `gr.spline` draws a cubic spline. sometimes (for histograms etc) it's nice to have a line that does a 'constant interpolation', i.e. looks like a staircase up or down. the function would need an optional argument that specifies if the interpolation is to the previous y value, the next y value, or a nearest-neighbor rule.

**Comment by nilsbecker** [comment]
(one could also think of adding quadratic splines, so that all interpolation orders 0-3 are covered)

**Comment by nilsbecker** [comment]
for reference:

https://matplotlib.org/api/_as_gen/matplotlib.pyplot.step.html

one might argue that this is more high-level than the bare gr plotting functions? i still think it might be useful also to have available

**Comment by FlorianRhiem** [comment]
Yes, this is probably something for `mlab` and `jlgr` instead of gr itself.

Here's an example of a plot like this for the `where=mid` setting in `matplotlib.pyplot.step` with gr, other `where` settings require less manipulation of the input data and also boil down to a polyline:
```
import numpy as np
import gr

x = np.linspace(-2 * np.pi, 2 * np.pi, 30)
y = np.cos(x)

n = len(x)
x_steps = x[1:] - x[:-1]
x_step_boundaries = np.zeros(2 * n)
x_step_boundaries[0] = x[0] - (x[1] - x[0]) / 2
x_step_boundaries[1:-1][0::2] = (x[1:] + x[:-1]) / 2
x_step_boundaries[1:-1][1::2] = (x[1:] + x[:-1]) / 2
x_step_boundaries[-1] = x[-1] - (x[-1] - x[-2]) / 2
y_step_values = np.zeros(2 * n)
y_step_values[0::2] = y
y_step_values[1::2] = y

gr.setwindow(-2 * np.pi, 2 * np.pi, -1, 1)
gr.axes(0.5, 0.25, -2 * np.pi, -1, 4, 2, -0.0075)
gr.polyline(x_step_boundaries, y_step_values)
gr.updatews()
```
![image](https://user-images.githubusercontent.com/4411847/47135668-7d6add80-d2b1-11e8-9c09-11dc74cd08de.png)

**Comment by nilsbecker** [comment]
i agree it's not overly hard to implement yourself on the basis of polyline but it would be nice to have this as a built-in function since it's needed every now and then and it's annoying to have to redo manually.

**Comment by FlorianRhiem** [comment]
`mlab.step()` will be part of the next release of [python-gr](https://github.com/sciapp/python-gr). Here's a demo of the `where` parameter's effect:
![gks](https://user-images.githubusercontent.com/4411847/47280163-5d029200-d5d5-11e8-9c65-94ebccc1f2c3.png)

**Comment by nilsbecker** [comment]
cool! thanks!
