### ISSUE TITLE
Error during install from Pypi

### ISSUE THREAD

**Issue by jfmoulin** [sciapp/gr#74]
On linux, under python 3.6.7, I could not install via pip, see trace below:

    collecting gr
      Downloading https://files.pythonhosted.org/packages/95/4b/37577043a27b692178eaf9166963f30d9abfe0b2a4a82f43998670fb5f2f/gr-1.7.1.tar.gz (89kB)
        100% |████████████████████████████████| 92kB 563kB/s 
    Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.6/dist-packages (from gr) (1.14.5)
    Installing collected packages: gr
      Running setup.py install for gr ... error
        Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-s0mk28t5/gr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-g22xq_n6/install-record.txt --single-version-externally-managed --compile:
        running install
        running build
        running build_py
        creating build
        creating build/lib
        creating build/lib/gr
        copying gr/runtime_helper.py -> build/lib/gr
        copying gr/_version.py -> build/lib/gr
        copying gr/__init__.py -> build/lib/gr
        creating build/lib/gr3
        copying gr3/__init__.py -> build/lib/gr3
        creating build/lib/qtgr
        copying qtgr/backend.py -> build/lib/qtgr
        copying qtgr/__init__.py -> build/lib/qtgr
        creating build/lib/gr/matplotlib
        copying gr/matplotlib/backend_gr.py -> build/lib/gr/matplotlib
        copying gr/matplotlib/__init__.py -> build/lib/gr/matplotlib
        creating build/lib/gr/pygr
        copying gr/pygr/helper.py -> build/lib/gr/pygr
        copying gr/pygr/mlab.py -> build/lib/gr/pygr
        copying gr/pygr/base.py -> build/lib/gr/pygr
        copying gr/pygr/__init__.py -> build/lib/gr/pygr
        creating build/lib/qtgr/events
        copying qtgr/events/mouse.py -> build/lib/qtgr/events
        copying qtgr/events/gestures.py -> build/lib/qtgr/events
        copying qtgr/events/base.py -> build/lib/qtgr/events
        copying qtgr/events/__init__.py -> build/lib/qtgr/events
        running egg_info
        writing gr.egg-info/PKG-INFO
        writing dependency_links to gr.egg-info/dependency_links.txt
        writing requirements to gr.egg-info/requires.txt
        writing top-level names to gr.egg-info/top_level.txt
        reading manifest file 'gr.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        warning: no previously-included files matching '__pycache__' found anywhere in distribution
        warning: no previously-included files matching '*.db' found anywhere in distribution
        writing manifest file 'gr.egg-info/SOURCES.txt'
        error: [Errno 21] Is a directory: '/etc/upstream-release'
        
        ----------------------------------------
    Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-s0mk28t5/gr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-g22xq_n6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-s0mk28t5/gr/

**Comment by danielkaiser** [comment]
Hello jfmoulin,
there was an issue in the `setup.py` script on systems that have a `/etc/upstream-release` directory like Linux Mint (and probably other Ubuntu based distributions). It should be fixed in [python-gr release 1.7.2](https://pypi.org/project/gr/1.7.2/) that is now available on PyPI.

**Comment by danielkaiser** [comment]
Hello jfmoulin,
have you already tried installing the new version and if so, did this resolve the problem?
