### ISSUE TITLE
C API error handling

### ISSUE THREAD

**Issue by v0dro** [sciapp/gr#76]
I searched the code base but could not find any standardized way in which GR handles errors. Most C libraries that I've worked with in the past return some integer value from functions in case they fail.

What sort of mechanism is followed for this purpose in GR? Am I missing something?

**Comment by FlorianRhiem** [comment]
The current error handling mostly consists of reporting the error and if there is no way of recovery (e.g. when the system is out of memory), aborting the program.

- For GR errors are reported to `stderr`, or handled by GKS if the data is simply passed through to it.
- For GKS there is `gks_perror` and related functions (like `gks_report_error` and `gks_fatal_error`) in [error.c](https://github.com/sciapp/gr/blob/master/lib/gks/error.c).
- For GR3 there is `gr3_geterror` and `gr3_geterrorstring`, which translate more easily into exceptions in wrappers, e.g. in [python-gr](https://github.com/sciapp/python-gr/blob/94a979494737081ad0414d69379fa21e854d988f/gr3/__init__.py#L228).
