### ISSUE TITLE
Julia gksqt binary on tumbleweed

### ISSUE THREAD

**Issue by j-fu** [sciapp/gr#94]
Hi, since my last update to openSUSE Tumbleweed, the gksqt ceased to work (from Julia). Reinstallation didn't help. It was missing libQtGui.so.4. 
Obviously this  is linked to [KDE4/Qt4 being removed from the distro](http://dominique.leuenberger.net/blog/2019/10/opensuse-tumbleweed-review-of-the-week-2019-43/).
I cloned gr and recompiled it  (via Makefile), overwrote the gksqt in .julia and it works. So it seems that all what is needed is to tweak the packaging  accordingly.

Jürgen

**Comment by FlorianRhiem** [comment]
Hello, we do not build binaries for Tumbleweed, so the generic Linux binaries (built on/for CentOS 6) are used. Do the [binaries for CentOS 7](https://gr-framework.org/downloads/gr-0.44.0-CentOS-x86_64.tar.gz) work on your system?

**Comment by j-fu** [comment]
Yes, they do. How to fake my system ID then ?  Is there a list of supported systems to try ?


Anyway I mean I am fine for myself as you see in my initial post, but I am a bit worried about the less experienced. Of course tumbleweed is not for them and as we see it is a moving target...  This is more or less a general concern on how Julia can work with binary dependencies and I know it is not easy.

**Comment by FlorianRhiem** [comment]
The wrappers check `/etc/os-release` (among others) to detect which distribution the user is running. In case of Tumbleweed, checking for `ID="opensuse-tumbleweed"` in `/etc/os-release` should do the trick.

**Comment by FlorianRhiem** [comment]
I've added this check to [python-gr](https://github.com/sciapp/python-gr/commit/14d5638b50701164f59026a2052f99037ffa8ee1) and [GR.jl](https://github.com/jheinen/GR.jl/commit/d49766d14dd82f807e746eaea7ed713f7a7bf123), so this issue will be fixed the next time these packages are released.
