### ISSUE TITLE
Function name `gr_volume` looks special

### ISSUE THREAD

**Issue by kojix2** [sciapp/gr#95]
Hello.
I noticed that it is not `gr3_volume`.
This is the only function that start with `gr_` in gr3. It looks special.

https://github.com/sciapp/gr/blob/10a726a5a6e9973e93ab02ec0869733d97378cb6/lib/gr3/gr3.h#L242

But I don't know if this is a typo or not.
So I open and close the issue...

**Comment by FlorianRhiem** [comment]
Hey,
the reason this GR function is part of libGR3 is that is currently requires OpenGL and GR3 already manages OpenGL context detection/creation. As we didn't want GR to require GR3 (which would result in a circular dependency), we decided to compile/link it as part of libGR3.

**Comment by kojix2** [comment]
I understand. 
Thank you for your clarification :+1:
